CHAR_MAX_LEN: int = 256
SLUG_MAX_LEN: int = 256
YEAR_MIN: int = 1000
RATING_MIN: int = 0
RATING_MAX: int = 10
INVALID_YEAR: str = "You can't add works that haven't been released yet"
TITLE_VERBOSE_NAME: str = 'произведение'
TITLE_VERBOSE_NAME_PLURAL: str = 'произведения'
GENRE_VERBOSE_NAME: str = 'жанр'
GENRE_VERBOSE_NAME_PLURAL: str = 'жанры'
CATEGORY_VERBOSE_NAME: str = 'категория'
CATEGORY_VERBOSE_NAME_PLURAL: str = 'категории'
SLUG_VERBOSE_NAME: str = 'уникальная строка'
NAME_VERBOSE_NAME: str = 'название'
TITLE_YEAR_VERBOSE_NAME: str = 'год выпуска'
TITLE_DESCRIPTIONS_VERBOSE_NAME: str = 'описание'
VERBOSE_NAME_AUTHOR: str = "автор"
VERBOSE_NAME_TEXT: str = "текст"
VERBOSE_NAME_PUB_DATE: str = "дата публикации"
VERBOSE_NAME_REVIEW: str = "отзыв"
VERBOSE_NAME_REVIEW_PLURAL: str = "отзывы"
VERBOSE_NAME_SCORE: str = "оценка"
VERBOSE_NAME_COMMENT: str = "комментарий"
VERBOSE_NAME_COMMENT_PLURAL: str = "комментарии"
RATING_MIN_VALIDATE: str = "Оценка не может быть меньше 0"
RATING_MAX_VALIDATE: str = "Оценка не может быть больше 10"
