CHAR_MAX_LEN: int = 256
SLUG_MAX_LEN: int = 256
YEAR_MIN: int = 1000
RATING_MIN: int = 0
RATING_MAX: int = 10
VERBOSE_NAME_AUTHOR: str = "автор"
VERBOSE_NAME_TEXT: str = "текст"
VERBOSE_NAME_PUB_DATE: str = "дата публикации"
VERBOSE_NAME_TITLE: str = "произведение"
VERBOSE_NAME_TITLE_PLURAL: str = "произведения"
VERBOSE_NAME_REVIEW: str = "отзыв"
VERBOSE_NAME_REVIEW_PLURAL: str = "отзывы"
VERBOSE_NAME_SCORE: str = "оценка"
VERBOSE_NAME_COMMENT: str = "комментарий"
VERBOSE_NAME_COMMENT_PLURAL: str = "комментарии"
RATING_MIN_VALIDATE: str = "Оценка не может быть меньше 0"
RATING_MAX_VALIDATE: str = "Оценка не может быть больше 10"
