# Generated by Django 3.2 on 2024-07-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='score',
        ),
    ]
